# Generated by Django 2.1.2 on 2019-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20191026_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemodel',
            name='id',
            field=models.CharField(default='line_201910271634194d27522b', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='id',
            field=models.CharField(default='route_2019102716341997b1a6a2', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
