version: '3.7'

services:
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - web-static:/home/app/web/static
    expose:
      - 8000
    env_file: .env
    command: gunicorn urbvan.wsgi --bind 0.0.0.0:8000
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./config/nginx
    volumes:
      - web-static:/home/app/web/static
    ports:
      - 8000:8000
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: ./config/db/.env

  redis:
    restart: always
    image: redis:5.0.6-alpine
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata: